- .gitignore
- .packit.sh
- .packit.yaml
- Makefile
- qm-selinux.spec.rpkg
- qm_selinux.8
This commit adds Packit configuration files which will trigger builds on
copr:`rhcontainerbot/packit-builds` on every PR and on
copr:`rhcontainerbot/podman-next` on every commit to main branch.
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
> Packit: initial enablement

- .packit.yaml
This section doesn't work as expected yet, so builds on `rhcontainerbot/podman-next` copr will be triggered using a webhook.
> Packit: Comment out `trigger: commit` block

- qm.container
In RHIVOS we want to support running VMs and specifically Android within the QM, which requires /dev/kvm to be present.
> Add /dev/kvm device to qm, so VMs can be launched

- setup
Attempt to first copy the /etc/hirte/agent.conf from the host into the hirte environmnet, and add qm. to the front of the NodeName field.
If the NodeName field does not exists or is emtpy, then add qm.HOSTNAME as the NodeName.
If the NodeName is qm., then add HOSTNAME to the end.
> Automatically setup the hirte-agent

- qm.container
This is required on environments like VMs where /dev/kvm is not present.
@rhatdan @alexlarsson PTAL
> quadlet: make `/dev/kvm` optional

- qm.spec.rpkg
> RPM: set AllowedCPUs in quadlet file post install

- qm.container
Set `AllowedCPUs=` to a minimal sane default which should work for most if not all users.
RPM packaging can optimize this for the env in postinstall.
@rhatdan PTAL
> quadlet: minimal sane default for AllowedCPUs

- .packit.sh
- .packit.yaml
- rpm/qm.spec
- rpm/update-spec-version.sh
Get rid of `qm.spec.rpkg` in favour of
`rpm/qm.spec` which gets synced with fedora dist-git on every upstream release. The version in the new spec file is set to `0` by default and gets updated by packit automatically on every packit task.
For local manual rpm builds using the spec, the helper script in the `rpm/` subdir will update the Version field with the latest version found in the upstream repo.
Packit will automatically create a PR on fedora dist-git on every new upstream release. A sample PR will look like:
https://src.fedoraproject.org/rpms/container-selinux/pull-request/10#
A dry run for this can be triggered using:
`$ packit propose-downstream --local-content`
To run this command locally, you would need to have your packit user-configuration-file set.
Ref: …
> Packit: Add downstream Fedora packaging tasks

- setup
We want to configure storage inside of the qm to use transient store.
Setup /var/lib/shared directory to be available to be volume mounted from the host, if it is not volume mounted then we need to make sure the storage still works.
> Add configuration of storage.conf for qm

- tests/e2e/.gitignore
- tests/e2e/ContainerFile.control
- tests/e2e/README.md
- tests/e2e/lib/container
- tests/e2e/lib/systemd
- tests/e2e/lib/tests
- tests/e2e/lib/utils
- tests/e2e/run-test-e2e
```
$ ./run-test-e2e
[ INFO ] Starting setup
[ INFO ] ==============================
[ INFO ] Cleaning any previous e2e files
[ INFO ] Creating podman network [netcow]
[ INFO ] Preparing ASIL environment
[ INFO ] ==============================
[ INFO ] Creating container control [ASIL mode]
[ INFO ] Creating stub systemd service: container-safety in container control
[ INFO ] Creating stub systemd service: container-cruise_control in container control
[ INFO ] Creating stub systemd service: container-tires in container control
[ INFO ] Creating stub systemd service: container-breaks in container control
[ INFO ] Preparing QM environment
[ INFO ] ==============================
[ INFO ] Creating container node1 [QM mode]
[ INFO ] Creating containers radio, maps, store
[ INFO ] See: …
```
> e2e: Initial e2e code

- setup
The lines documenting what the script does (at the beginning of the script) were pointing to the wrong path/folder being created by this script.
This patch fixes that path to be the correct one
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>
> Quick doc fix in the setup script

- setup
Seemed to be a temporary bug in fedora 38
> No longer need the --nogpgcheck flag

- tests/e2e/ContainerFile.control
- tests/e2e/lib/container
- tests/e2e/lib/systemd
- tests/e2e/lib/tests
- tests/e2e/run-test-e2e
- Add ability to build hirte from source and selecting branch automatically. Helps to do e2e in different branches and releases.
- Few others improvements and reduced extra work needed.
- Added --build-from-qm source too (needs to be finished.)
> e2e: add initial getopt

- qm.container
With the current code using builtin volumes users on the host system can not modify the ROOTFS/var and ROOTFS/etc directories.
This PR just remounts these directories on top of themselves read/write allowing users from the host to modify the directories and the processes inside of the container to modify them.
Both the host and the QM will be able to see the modifications.
Added a ROOTFS=/usr/lib/qm/rootfs environment variable to make the quadlet easier to understand.
> Fix handling of /var and /etc within container

- .packit.yaml
- rpm/qm.spec
Podman v4.5 and hirte-agent are not yet available on epel9 so this commit removes those dependencies for epel9 and leaves it to the user to fetch those.
Bodhi updates are also disabled so the built package never gets submitted to any yum repo.
Refs:
1. https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2023-77d64cf134#comment-3026157
2. https://github.com/containers/qm/pull/59#issuecomment-1551691316
> Packit: Temporarily disable bodhi for epel9

- tests/e2e/ContainerFile.control
- tests/e2e/README.md
e2e tests failed consistently on CentosStream9 with errors Error: netavark: code: 3, msg: modprobe: FATAL: Module ip ptables v1.8.8 (legacy): can't initialize iptables table
Updating Readme/requirements to consume latest:
podman
hirte
> Updating images iptables-services

- tests/e2e/lib/systemd
Just found these errors executing dualstack tests.
> systemd: fix bash errors

- rpm/qm.spec
Otherwise we end up with a file in /etc/containers/systemd that isn't linked in the RPM database to the qm package making people wonder where this is coming from.
> Make %ghost own the file created in %post

- qm.container
Added Install section as per
https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html in order to get the container up after reboot.
Fixes #105
> start qm.service at boot

- setup
previously qm.service was stopped always, including when reconfiguring hirte-agent at qm.service start.
Now qm.service is stopped only if a real install is being executed.
Fixes #106
> stop qm.service only on real install

- tests/e2e/dashboard-tui/car-dashboard
- tests/e2e/lib/tests
- tests/qm-connectivity/test.sh
```
[root@dell730 qm]# pre-commit run --all-files
trim trailing whitespace.................................................Passed
shellcheck...............................................................Passed
markdownlint.............................................................Passed
flake8...................................................................Passed
```
> tests: fix pre-commit warnings in bash/python

- qm.container
> qm.container: remove ExecuteStartPre

- README.md
- rpm/qm.spec
explicitly require `golang-github-cpuguy83-md2man` instead of `%{_bindir}/go-md2man` and added a note about where to find it on CentOS Stream 9.
Fixes #120
> spec: require golang-github-cpuguy83-md2man

- rpm/qm.spec
Nothing bad but let's remove the errors from rpmlint.
Resolves: https://github.com/containers/qm/issues/121
> spec: remove errors in the spec

- tests/e2e/lib/container
In this moment of the deploy, this option is not commented. Fixing the sed.
> e2e: remove commented line in the AllowedNodeNames

- tests/e2e/run-test-e2e
To test hirte and qm in scale we will need a way to easily create 'N' nodes.
Example for creating 8 nodes with 8 qm containers inside:
./run-test-e2e --number-of-node=8
> e2e: run-test-e2e add --number-of-nodes

- tests/e2e/run-test-e2e
- the network creation can show an error like "network already exists"
- sysctl stdin output can be ignored as well
> e2e: ignore some outputs

- tests/e2e/lib/container
Hirte has the maximum length per line in the configuration.
The limit is 500 or use the multiline approach for long lines.
More info:
https://github.com/containers/hirte/blob/main/doc/docs/configuration.md#maximum-line-length
> e2e: handle multiline in hirte.conf

- tests/e2e/tools/README.md
- tests/e2e/tools/remove-containers
remove all containers/image which name start with node* or control from the output of podman ps.
Useful to cleanup environments before measures.
> e2e: add tool remove-containers.sh

- .packit.yaml
- rpm/qm.spec
This reverts commit 1cfd9786d41edd0f9d91bc433799c9460bfded3e.
Now podman 4.6 is included in CentOS Stream 9
Fixes #146
> partially revert commit 1cfd978

- .packit.yaml
I removed them in commit 62c1ee9f17 with ignoring that this is a deliberate subset of targets, as this project doesn't build in e.g. Fedora 37 or C8S. Put them back.
-----
I was checking [recent podman-next builds](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/builds/) after the landed packit PRs today, and noticed the [build failures](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6257432/). Sorry for the blunder!
[This is the net diff](https://github.com/containers/qm/compare/a44f687e4285949e270137f00e8dc07d22975678..0cace9f6b9bd780c7e35de684d4ba62102cd4232#diff-2b4300f6d69654fd71c0cdd329b5a5f13fa8fe7eb709c76276bdfd3ea1dde578) of packit.yaml between  before PR #160 and this (ignore the tests/e2e bits, that PR landed in between)
@lsm5
> packit: Restore podman-next target list

- tests/e2e/lib/ContainerFile.template
> e2e: add packages for tmt development

- .packit.yaml
PTAL.
podman v4.6 and hirte are now available on C9S, so we should be ok. Will the hirte / bluechi name be an issue?
FYI, the distro targets will become a lot easier to manage once fedora-37 is EOL.
> Packit: Enable fedora-39 targets and bodhi for epel-9

- setup
Tiny fix to make the `--skip-systemctl` flag to work as expected.
> fixing --skip-systemctl param

- tests/e2e/lib/ContainerFile.template
go-toolset provides the Go programming language tools and libraries.
Fixes: https://github.com/containers/qm/issues/191
> e2e: add go-toolset

- Makefile
- build-aux/validations
The script was failing when getting "9.2" in VERSION_ID.
> build: adjust make to handle floats in os-release

- tests/e2e/lib/ContainerFile.template
Fixes: https://github.com/containers/qm/issues/195
> e2e: add ruby to the containers image

- tests/e2e/lib/ContainerFile.template
> e2e: add markdown-cli linter

- tests/e2e/lib/ContainerFile.template
dbus-devel provides libraries and header files needed for developing software that uses D-BUS.
> e2e: Add dbus-devel package

- tests/e2e/lib/container
Resolve images issue in  https://github.com/containers/qm/issues/164
This PR fix the creating multi images for many nodes,
Now all node container should use node image.
> Running single container for nodes containers

- qm.container
The default limit on number of processes within the container is 2048. This is far too low for QM. Selecting 50% of max seems like a better number but really this needs to be set by the final distributor of the OS.
Also set the maximum number of open file descriptors.
> limit the number of processes/tasks inside of the QM

- tests/e2e/README.md
- tests/e2e/lib/tests
- tests/e2e/tier-0.fmf
- tests/qm-connectivity/main.fmf
The test run prepare step only on c9s and fedora
ENV variables changed based on the distro it is inquires.
Please take a look here for tmt extra keyes
https://tmt.readthedocs.io/en/latest/spec/core.html#adjust
> Updating tests to work against qm AutoSD image

- tests/e2e/tools/FFI/README.md
- tests/e2e/tools/FFI/disk/file-allocate.c
- tests/e2e/tools/FFI/memory/ASIL/20_percent_memory_eat.c
- tests/e2e/tools/FFI/memory/QM/90_percent_memory_eat.c
Just an initial code for FFI:
- Add C sources to eat memory (ASIL: 20) (QM: 90)
- file-allocate source
> Add support to FFI

- tests/e2e/lib/container
- tests/e2e/lib/systemd
- tests/e2e/lib/utils
- tests/e2e/run-test-e2e
Mostly cosmetic changes:
- be consistent in terms of tabs vs spaces
- consistent indentation depths
- use `local` variables
- only color output when the terminal signals support
- use variables for the color control sequences
- use heredoc instead of many `echo`s
- small fixes to the help message
> Cleanup scripts

- qm.container
Based on latest changes
This resolves #226
qm.service failes to load
ignoring: unsupported key 'SecurityLabelNested' in group 'Container'
> Update nodeX container file

- setup
- tests/e2e/run-test-e2e
Adds `skip-systemctl,` so it can work with other cli options.
> fix using skip-systemctl with other options

- tests/e2e/tools/FFI/Makefile
Adding missing Makefile from early merge
https://gitlab.com/CentOS/automotive/container-images/-/blob/main/images/ffi-tools/Containerfile?ref_type=heads#L16
> Adding Makefile for ffi-tools container

- .packit.yaml
- tests/e2e/lib/tests
- tests/e2e/tier-1.fmf
- tests/qm-connectivity/main.fmf
Resolves #236
Add tier-1 tmt test
Verifies QM https://quay.io/repository/centos-sig-automotive/autosd
is up and running
> Add CI test verify Quay AutoSD QM is working

- .packit.yaml
- setup
moving from /etc/bluechi/agent.conf ->
/etc/bluechi/bluechi/agent.conf.d/
resolve #248     
since e2e/tier-1 test AutoSD image health, 
This PR will not pass tests till autosd image build upload latest image https://gitlab.com/CentOS/automotive/container-images.git    
depends #251
> Fixing location of agent.conf

- tests/e2e/lib/ContainerFile.template
- tests/e2e/lib/container
e2e tier-0 started to fail probably due to updates in
Bluechi Configuration files
Updating config files in e2e tests setup
moving from /etc/bluechi/agent.conf ->
/etc/bluechi/agent.conf.d/
moving from /etc/bluechi/controller.conf ->
/etc/bluechi/controller.conf.d/
> Apply changes of bluechi configs in e2e containers

- .packit.yaml
- plans/e2e/ffi.fmf
- tests/e2e/README.md
- tests/e2e/set-ffi-env-e2e
- tests/qm-connectivity/main.fmf
Set testing infra for ffi
resolves partly #233
The following setup script, set identical deploy topology for:
AutoSD.qcow2 image
autosd container
c9s
FFI tests run against unified test topology.
Adding FFI plan/e2e
install qm env inside c9s host and run qm-connectivity through
ffi filter
depends #249
> FFI test infra

- tests/e2e/lib/ContainerFile.template
- tests/e2e/set-ffi-env-e2e
Resolve 1st issue in #253 
CI started to FAIL on dnf install
Unable to find a match: tmt-report-junit, removed it for now
CI failing due to curl configuration files, which are not accessible to public.
Replace curl configuration of bluechi entities with coded default config
> Fix ContainerFile.template errors

- tests/e2e/lib/container
Currently, e2e is failing with timeout as the AllowedNames is not set correctly.
> e2e: adjust the path for controller.conf

- plans/e2e/ffi.fmf
- tests/e2e/README.md
- tests/e2e/lib/utils
- tests/e2e/set-ffi-env-e2e
- tests/e2e/tools/README.md
- tests/ffi/memory/main.fmf
- tests/ffi/memory/prepare.sh
- tests/ffi/memory/test.sh
- tests/qm-connectivity/test.sh
~This PR is dependent with PR #210,~
~Do not merge~
> FFI test containerfile

- tests/e2e/lib/utils
- tests/e2e/run-test-e2e
- tests/e2e/tools/remove-containers
> e2e: improve cleanup call

- tests/e2e/lib/container
We had cases where ManagerHost in node{ID} is not updated with what qm container contain as ManagerHost. This happens as the ContainerFile.node can be generated days/hours/minutes before the qm container be in fact created.
> e2e: always update ManagerHost

- tests/e2e/lib/ContainerFile.template
To avoid container startup issues with iptables legacy let's make sure control and node1 contain iptables-nft.
> e2e: add iptables-nft to control/nodeX nodes

- setup
RHEL kernel uses iptables-nft, not iptables-legacy.
> setup: make sure we have iptables-nft

- setup
add vim editor to the qm container
> setup: add vim

- setup
Reduce the attack surface, for tests we can create a different mechanism to install the packages.
> setup: remove vim and findutils

- tests/e2e/lib/quadlet/container-template.container
- tests/e2e/lib/systemd
podman generating systemd services is deprecated.
This patch uses quadlet container file to reproduce an auto environment in a nested container.
> e2e: replace systemd stubs with quadlet

- plans/e2e/ffi.fmf
- tests/ffi/qm-unit-files/main.fmf
- tests/qm-unit-files/main.fmf
- tests/qm-unit-files/test.sh
PR propose tests resolve #216 
Add new test qm-unit-files
> Add test qm-unit-files

- tests/e2e/README.md
Update with some more data, related grow mounted filesystem
> Updating test README.md

- .packit.yaml
- plans/e2e/ffi.fmf
- plans/e2e/tier-0.fmf
- setup
- tests/e2e/lib/ContainerFile.template
- tests/e2e/lib/container
- tests/e2e/lib/systemd
- tests/e2e/run-test-e2e
- tests/e2e/set-ffi-env-e2e
Resolves #290 and Resolves #288 
Currently tests are not using packit repo created by previous steps Added an option for scripts --use-qm-copr to 
For containers build, if PACKIT_COPR_PROJECT exist while running under packit pipeline, the repo is enabled and install PR qn rpm
be used while running tests with rhcontainerbot/qm, default is using packit rpms, triggered by scenario=manual parsed in context scenario == manual
> Fix current run-test-e2e

- rpm/qm.spec
- setup
- tests/e2e/lib/tests
- tests/e2e/set-ffi-env-e2e
rename hirte-agent -> bluechi-agent
Resolve #293 
Adding fix related to CopyTmpImages dir was non under the right section
Adding fix for renaming /var/qm partition -> /var
Adding fix, for umount $ROOTFS/var $ROOTFS/etc it is called to earl,y thus could not create files/vars under 
$ROOTFS/var directory
> Updating old dependency in hirte-agent

- tests/e2e/set-ffi-env-e2e
- tests/ffi/agent-flood/main.fmf
- tests/ffi/agent-flood/test.sh
- tests/ffi/common/prepare.sh
Resolves #292 
test is running 2 bluechi-testers on qm, through quadlet.
test is checking for asil bluechi-agent connection
> Add bluechi-agent flood test

- tests/e2e/lib/ContainerFile.template
Now it's possible to run bluechi stress test
> lib: add python3-dasbus into Container template

- qm.container
There is errors running podman (OCI permission denied) limiting the environment. Comment for now.
See-Also: https://github.com/containers/crun/issues/1388
> qm.container: comment DropCapability

- .pre-commit-config.yaml
- demos/asilservice
- demos/demo
- setup
- tests/e2e/lib/ContainerFile.template
- tests/e2e/lib/container
- tests/e2e/set-ffi-env-e2e
resolve #310 
Current regexp creates malformed podman
storage.conf file for qm, which breaks podman cli inside QM
> Adding setup fix

- tests/e2e/lib/container
- tests/e2e/run-test-e2e
With recent changes all nodes generated had node1 as name.
Fixes: https://github.com/containers/qm/issues/301
> e2e: fix nodename in nodes

- .packit.yaml
resolve #322 
It seems that release stage is failing due to vsomeip3-selinux
> Adding epel dependency for packit relase stage

- rpm/qm.spec
vsomeip is not available on all required platforms, so if needed we can
pass `with_vsomeip 0` to rpmbuild to disable vsomeip dependency.
resolve #324 
Signed-off-by: Martin Perina <mperina@redhat.com>
> Make vsomeip dependency optional

- plans/e2e/ffi.fmf
- tests/e2e/set-ffi-env-e2e
Adding support for testing against
SoC HW with distro=centos-stream-automotive-9
> Adding fixes base on QC SoC

- setup
Resolves #333 
In case QM ${ROOTFS}/etc/yum.repos.d is empty
Add AutoSD repo in order to setup QM on aarch64 SoC
seems that the following configuration in qm storage.conf on ro filesystem causes podman cli errors
additionalimagestores = [
"/var/lib/shared/",
"/usr/lib/containers/storage",
]
removing the ro part from additional images
> Adding ROOTFS repo dir check

- setup
- tests/e2e/set-ffi-env-e2e
- tests/ffi/agent-flood/test.sh
- tests/ffi/common/prepare.sh
last fixes after rerunnig on clean arm64
Adding option to run with AutoSD, release repos
Once setting PACKIT_COPR_PROJECT=release
> Fixes related to arm64

- tests/e2e/tools/FFI/Makefile
- tests/e2e/tools/FFI/shared-memory/shm.c
Added shared memory test to tools/FFI
> add shm to ffi tools

- qm.container
- rpm/qm.spec
- setup
Patch originally from talk with @alexlarsson
> qm: add seccomp json also deny sched_setscheduler

- tests/e2e/tools/FFI/README.md
- tests/e2e/tools/FFI/sysctl/README
- tests/e2e/tools/FFI/sysctl/setsysctl
setsysctl is simple script that uses sysctl tool to try to change several parameters in the host OS.
It must be executed inside QM environment as a container (nested) to make sure attemps to change OS level are denied. Based in this tool, we can add it too the Container Image ffi-tools and generate tests.
> FFI: add setsysctl

- tests/e2e/tools/FFI/README.md
- tests/e2e/tools/FFI/deny_set_scheduler/README
- tests/e2e/tools/FFI/deny_set_scheduler/execute_set_scheduler.c
A tool to test if set_scheduler is denied inside QM partition.
> FFI: add tool test for execute_set_scheduler.c

- setup
if users try to run setup without installing QM package we should exit.
Fixes: https://github.com/containers/qm/issues/364
> setup: validate qm installation

- tests/e2e/tools/FFI/deny_sched_setattr/README
- tests/e2e/tools/FFI/deny_sched_setattr/execute_sched_setattr.c
A tool to test if inside QM it's possible to use the deny_sched_setattr() syscall to set SCHED_DEADLINE.
Fixes: https://github.com/containers/qm/issues/376
> tools: add deny_sched_setattr

- rpm/qm.spec
podman 5 is shipped already in EL9 platforms.
> spec: remove validation for podman package

- Makefile
- create-seccomp-rules
- rpm/qm.spec
- setup
This patch removes the logic from setup and creates a independent tool to manage seccomp rules for QM. It should help with ostree issue.
Fixes: https://github.com/containers/qm/issues/385
Fixes: https://github.com/containers/qm/issues/375
> seccomp: add new tool create-seccomp-rules

- Makefile
- rpm/qm.spec
- tools/comment-tz-local
In recent tests with ostree + quadlet environment the QM service was not able to work correctly, podman failed to remove /etc/localtime affecting the QM service. This patch is a workaround to Timezone=local which uses Environment=TZ to set the default timezone to UTC until we work in root cause.
More information: #367
Fixes: #367
> qm.container: replace tz=local in ostree distro

- setup
We should validate if the packages exists to avoid exit in failed command.
Fixes: https://github.com/containers/qm/issues/396
> setup: add validation for removing PACKAGES_TO_REMOVE

- README.md
Got few questions regarding selinux, getting the output of some debugging tools in hand can save time to everyone. Let's make it available to users via README.
Fixes: https://github.com/containers/qm/issues/389
> README: add some commands for selinux help

- qm.container
Change network option to private as default option
Fixes: https://github.com/containers/qm/issues/408
> qm.container: change default network option

- create-seccomp-rules
- tools/cicd-example-using-seccomp-rules
This global array can be loaded externally into tools to check if programs can be added into QM image/yaml that are not allowed or won't work into the QM partition.
In this case: "sched_setscheduler" and "sched_setattr" which QM engineers are following the Risk Assessments rules.
Projects like CentOS Automotive Stream Distribution could be take advanced in the CI/CD pipeline.
Finally, added an example in tool, how could be used in a CI/CD scenario such integration.
> seccomp: use SYSCALLS_TO_DENY array

- Makefile
- qm.8.md
- rpm/qm.spec
- setup
- tools/qm-storage-settings
setup calls storage() function to execute the initial storage configuration but it's not called during the ostree deploy as it's required to call /usr/share/qm/setup. This patch extract the logic from setup with few improvements and now can be called externally via ostree / osbuild / osbuild-auto.
> tools: add qm-storage-settings

- tests/ffi/agent-flood/main.fmf
- tests/ffi/agent-flood/test.sh
Right now due the change Host=private this test is failing. Let's skip until we fix it.
> tests: skip agent-flood test

- .packit.yaml
This commit switches to using podman-next's default repos so we don't have to worry about managing targets here.
> Packit: Use podman-next's default repos

- setup
- tests/e2e/lib/ContainerFile.template
- tools/qm-storage-settings
resolve #439 
Setup script or qm rpm does not call qm-storage-settings,
qm-storage-settings set qm storage.conf
Some more bash shell check fixes added
> Fix setup script

- tests/ffi/qm-oom-score-adj/main.fmf
- tests/ffi/qm-oom-score-adj/test.sh
Adding a ffi test to validate that que qm container main process runs with oom_score_adj = 500 and the qm containers processes runs with the om_score_adj = 750 by default
resolve #427
> ffi: Adding qm-omm-score-adj test

- tests/ffi/deny_set_scheduler/main.fmf
- tests/ffi/deny_set_scheduler/test.sh
Add tmt test case for tool "test_sched_setscheduler"  to verify that QM environment deny set_scheduler() syscall
resolve #365
> add deny_set_scheduler

- tests/ffi/sysctl/main.fmf
- tests/ffi/sysctl/test.sh
Adding a ffi test to execute sysctl inside nested container running on top of QM   
resolve #370  
Verify attempts to change OS level are denied inside QM container, like below
```shell
Setting sysctl parameters...
sysctl: permission denied on key "net.ipv4.ip_forward"
sysctl: permission denied on key "net.ipv4.conf.all.rp_filter"
sysctl: permission denied on key "net.ipv4.tcp_max_syn_backlog"
sysctl: permission denied on key "vm.swappiness"
sysctl: permission denied on key "vm.overcommit_memory"
```
> ffi: Adding sysctl test case.

- tests/ffi/modules/main.fmf
- tests/ffi/modules/test.sh
Adding a ffi test to check it won't be possible to access /lib/modules to load any module via modprobe inside the QM partition.
resolve #373 
Make sure it won't be possible to access /lib/modules to load any module via modprobe inside QM container, like below:
```
bash-5.1# modprobe ext4
modprobe: FATAL: Module ext4 not found in directory /lib/modules/5.14.0-438.391.el9iv.x86_64
bash-5.1# ls /lib/modules/5.14.0-438.391.el9iv.x86_64
ls: cannot access '/lib/modules/5.14.0-438.391.el9iv.x86_64': No such file or directory
```
> ffi: Adding modprobe modules case.

- tests/e2e/tools/FFI/Makefile
updated the `makefile` to add the tool `execute_sched_setattr` according to https://github.com/containers/qm/issues/377
> add execute_sched_setattr

- tools/generate-release-notes
A tool to generate release notes.  Anyone interested (Release Docs Team, PM, Developers or Owners of Projects)  can generate the release notes locally and do not depend on GitHub UI. 
```
Generating release notes from v0.6.2 to v0.6.4...
Collecting tags from https://github.com/containers/qm...
Checking if tags exist...
Fetching commit logs...
Categorizing commits...
Generating markdown output...
What's new:
==================
New (11):
- tools: add qm-storage-settings (Douglas Schilling Landgraf, Fri May 3 00:27:57 2024 -0400)
- Add initial policy type for wayland (Daniel J Walsh, Wed Apr 24 14:17:04 2024 -0400)
- seccomp: add new tool create-seccomp-rules (Douglas Schilling Landgraf, Wed Apr 24 23:45:39 2024 -0400)
- tools: add deny_sched_setattr (Douglas Schilling Landgraf, Tue Apr 23 …
```
> tools: generate-release-notes

- Makefile
- docs/devel/README.md
Add `make rpm` command in order to
run rpmbuild in a handy one-liner.
Configurable through certain env variables.
> makefile: build rpms

- tests/ffi/deny_sched_setattr/main.fmf
- tests/ffi/deny_sched_setattr/test.sh
Add tmt test case for tool "execute_sched_setattr" to verify that QM environment not allow SCHED_DEADLINE be set via sched_setattr() syscall
resolve https://github.com/containers/qm/issues/377
> add deny_sched_setattr

- docs/devel/README.md
Fixed typo in `Installing software inside QM partition` section of devel README
> Fixed typo in devel readme

- qm.if
Solve a connectto issue with ipc socket by calling `container_stream_connect` macro for the
`qm_container_ipc_t` label.
Closes: https://github.com/containers/qm/issues/468
> qm.if: allow stream connect for qm_container_ipc_t

- README.md
- docs/devel/README.md
- docs/quadlet-examples/virtualization/android/README.md
- qm.8.md
- tests/e2e/tools/FFI/README.md
- tests/e2e/tools/FFI/deny_sched_setattr/README.md
- tests/e2e/tools/FFI/deny_set_scheduler/README.md
- tests/e2e/tools/FFI/module/README.md
- tests/e2e/tools/FFI/sysctl/README.md
Fixed errors reported by markdown linter.
> Fixed markdown lint errors

- tests/ffi/common/prepare.sh
- tests/ffi/disk/test.sh
The prepare_test fuction overrides the OOMScoreAdjust value. That should be performed if necessary through systemd drop-in files.
> tests: Disable oom_score_adj on prepare_test

- build-aux/validations
- tests/e2e/dashboard-tui/car-dashboard
- tests/e2e/set-ffi-env-e2e
- tests/e2e/tools/FFI/deny_set_scheduler/execute_set_scheduler.c
- tests/e2e/tools/FFI/sysctl/setsysctl
- tests/ffi/deny_sched_setattr/test.sh
- tests/ffi/deny_set_scheduler/test.sh
- tests/ffi/qm-oom-score-adj/test.sh
- tests/ffi/sysctl/test.sh
addressed issues reported by pre-commit except:
```console
In create-seccomp-rules line 30:
--arg action "$action_type" \
^----------^ SC2154 (warning): action_type is referenced but not assigned.
```
reported at https://github.com/containers/qm/issues/476
> Address pre-commit reported issues

- qm.if
Fix syntax errors when running sepolgen-ifgen:
```
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 398 ) [type=CPAREN]
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 399 ) [type=CPAREN]
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 400 ) [type=CPAREN]
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 558 ' [type=SQUOTE]
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 621 ) [type=CPAREN]
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 622 ) [type=CPAREN]
/usr/share/selinux/devel/include/services/qm.if: Syntax error on line 623 ) [type=CPAREN]
```
> qm.if: fix syntax errors

- create-seccomp-rules
Addresses `action_type is referenced but not assigned` error. 
Removing action_type usage as suggessted in #476.
Fixes: #476
> create-seccomp-rules: remove action_type usage

- tools/qm-storage-settings
Adds a list of `containers/storage.conf` paths to look for instead of just one and returns early in case one is found.
resolve #481
> search path for containers/storage.conf

- .github/workflows/pre-commit.yml
- tools/qm-storage-settings
Fix missing double quoting in tools/qm-storage-settings
Fixes missing double quotes introduced in #479.
Not detected by pre-commit action as it's not configured  to run on all files.
```
In tools/qm-storage-settings fix for:
for STORAGE_CONF_PATH in ${STORAGE_CONF_PATHS[@]}; do
^----------------------^ SC2068 (error): Double quote array expansions to avoid re-splitting elements.
In tools/qm-storage-settings line 52:
if [ -f ${STORAGE_CONF_PATH} ]; then
^------------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
```
Then, enabling pre-commit on all files preventing this to happen again.
> Fix again pre-commit dected issues and turn test on for all files

- tests/ffi/agent-flood/main.fmf
- tests/ffi/agent-flood/test.sh
- updated the configuration of `/etc/qm/bluechi/agent.conf.d/agent.conf` to add  `ControllerHost `
- updated the quadlet files for testing containers to use controller host ip
So that the agent-flood test can run with qm private network
resolve https://github.com/containers/qm/issues/416
> update agent-flood based on the change of the default Network

- qm.if
Minimal set of SELinux rules to allow running Wayland compositor in the QM container.
> Add SELinux rules for Wayland

- tests/e2e/lib/container
- tests/ffi/common/prepare.sh
- tests/ffi/deny_sched_setattr/test.sh
- tests/ffi/deny_set_scheduler/test.sh
- tests/ffi/disk/test.sh
- tests/ffi/memory/main.fmf
- tests/ffi/memory/test.sh
- tests/ffi/modules/test.sh
- tests/ffi/qm-oom-score-adj/test.sh
- tests/ffi/sysctl/test.sh
TZ update to sync tier-0 testing
remove containers host containers from disk on cleanup
Remove qm.service update referencing to usage of drop-in files
fixes #451, fixes #462, fixes  #473
Signed-off-by: Yariv Rachmani <yrachman@redhat.com>
> test stability changes

- qm.if
Add remaining rules required to support
booting and running the wayland scenario,
with a compositor, session creation,
qm dbus management, and all required pieces.
Note that running pem_selinux for creating
the session will be blocked, as it falls back
to unconfined_u with the current rules.
> qm.if: add remaining wayland rules

- qm.if
Many times AVC's come in for certain interactions, without all of the possible AVCs. Changing to use patterns and _perms macros adds common patterns for allow rules, preventing many expected AVC's.
> Use pattern and _perms to make policy more resilient

- .packit.yaml
- plans/e2e/ffi.fmf
- plans/e2e/multi-bluechi-agents.fmf
- plans/e2e/tier-0.fmf
- plans/e2e/tier-1.fmf
- plans/main.fmf
- tests/e2e/set-ffi-env-e2e
- tests/qm-connectivity/main.fmf
- tests/qm-sanity-test/README.md
- tests/qm-sanity-test/check_bluechi_controller_is_ok.fmf
- tests/qm-sanity-test/check_bluechi_controller_is_ok.sh
- tests/qm-sanity-test/check_bluechi_is_ok.fmf
- tests/qm-sanity-test/check_bluechi_is_ok.sh
- tests/qm-sanity-test/check_qm_is_up.fmf
- tests/qm-sanity-test/check_qm_is_up.sh
- tests/qm-sanity-test/check_qm_podman_is_ok.fmf
- tests/qm-sanity-test/check_qm_podman_is_ok.sh
- tests/qm-sanity-test/check_qm_podman_quadlet_is_ok.fmf
- tests/qm-sanity-test/check_qm_podman_quadlet_is_ok.sh
- tests/qm-sanity-test/check_var_partition_exist.fmf
- tests/qm-sanity-test/check_var_partition_exist.sh
- tests/qm-sanity-test/main.fmf
- tests/qm-unit-files/main.fmf
We have several test cases for FFI, but we are missing some basic/simple sanity tests for qm, if it is installed properly and/or if environment started successfully. 
This is a draft version. Since the naming of the test files and test methods are simple, I hope to use this version as a starting point for improving the sanity test.
We would like to name this test plan tier-0, but need to rename the current tier-0 first, so I temporarily named it tier-2
resolve https://github.com/containers/qm/issues/342
> add tier-0 test case

- tests/ffi/qm-oom-score-adj/test.sh
Received a request to add additional information when the value do not match for oom-score-adj. Using this opportunity to improve this test code to have a constant.
> ffi: qm-oom-score-adj/test.sh improvement

- tests/ffi/dev_mem_not_present/PURPOSE
- tests/ffi/dev_mem_not_present/README.md
- tests/ffi/dev_mem_not_present/main.fmf
- tests/ffi/dev_mem_not_present/test.sh
I want ensure that /dev/mem is not accesible inside QM partition.
Test Design (improved based on PR review):
1. Using test expression in QM partition:
Execute the following command:
`podman exec qm test -e /dev/mem`
2. Expected Result:
/dev/mem does not exist, the command returns a non-zero value
3. Verify whether the test passed or not:
PASS: if the command returns a non-zero value, it means /dev/mem is not present
FAIL:  if the command returns 0, it means /dev/mem is present
> verify /dev/mem is not present in QM partition

- tests/ffi/tcp_max_syn_backlog/README.md
- tests/ffi/tcp_max_syn_backlog/main.fmf
- tests/ffi/tcp_max_syn_backlog/test.sh
Title: Validate if tcp_max_syn_backlog network parameter on Host can be resilient against random changes of this parameter in QM.
Description: The purpose of this test script is to validate if tcp_max_syn_backlog parameter value on Host, can be resilient against random changes of this parameter in QM. This is validated by creating a test environment, that generates and sets a random tcp_max_syn_backlog value in range from 128 to 1024 in QM and as soon as QM gets a new value, the test verifies that tcp_max_syn_backlog parameter on Host stays the same and not changes because of the QM network changes.
Expected result: PASS: tcp_max_syn_backlog parameter's value on Host stays the same.
Jira: VROOM-19564
> Add code to MR for tcp_max_syn_backlog test

- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/PURPOSE
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/README.md
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_console.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_console.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_disk.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_disk.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_kmsg.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_kmsg.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/PURPOSE
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/README.md
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_etc_qm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_etc_qm.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_lib_qm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_lib_qm.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_share_qm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_share_qm.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/PURPOSE
- tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/README.md
- tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/check_dev_shm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/check_dev_shm.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/PURPOSE
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/README.md
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_systemd_journal_socket.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_systemd_journal_socket.sh
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_udev_control.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_udev_control.sh
As the namespace is limited for the QM container, there is no method for an application to actively attempt to access a resource that is not present in the file system. Therefore it must be shown that the resources present in the file system match the expectations based on the configuration.
The QM partition configuration defines a set of available filesystem resources (devices, networks, shared memory, etc). These and only these resources are expected to be present in the QM partition's file system.
> Attempts to access forbidden file system resource

- tests/ffi/qm_nested/README.md
- tests/ffi/qm_nested/main.fmf
- tests/ffi/qm_nested/test.sh
This test is about running container named fedora inside the QM container (nested).
The test checks that nested container is running with proper name and that it is being created inside the QM container.
> Nested QM test to new fork

- tests/ffi/agent-flood/main.fmf
- tests/ffi/common/prepare.sh
- tests/ffi/deny_sched_setattr/main.fmf
- tests/ffi/deny_set_scheduler/main.fmf
- tests/ffi/memory/main.fmf
- tests/ffi/qm-oom-score-adj/main.fmf
1. When each test case is executed, if directory `/var/qm/lib/containers/registry` exists, delete it first, then create the directory and copy the `ffi-tools` container image to it.
2. Pulling `ffi-tools` image often times out, so extend the duration.
Resolve https://github.com/containers/qm/issues/506
> improve prepare_images and increase duration

- tests/ffi/common/prepare.sh
@dougsland suggested to add this patch to prepare.sh, so people will be able to init the ffi, by calling single init_ffi function, which includes all three functions (disk_cleanup,  prepare_test, at once in their code, reload_config), instead of calling 3 of them one by one in their code.
> Patch for common.sh

- tests/e2e/set-ffi-env-e2e
fix #511 
In case QM already runnig as a service
tests/e2e/set-ffi-env-e2e will exit 0
in case service does not exist,
it will contine
In case of ostree image script will exit
> add support in QM image

- tests/ffi/tcp_max_syn_backlog/test.sh
Patch to refine 2 message lines. Remove colors and make them simple.
> Refine comments in tcp_max_syn_backlog

- tests/ffi/agent-flood/test.sh
fix https://github.com/containers/qm/issues/517
Removed the code block for inserting `controller host ip` to /etc/qm/bluechi/agent.conf.d/agent.conf, because if `set-ffi-env-e2e` is not called, then this file may not exist. And the status of bluechi-agent `qm.localrootfs` does not affect the status of `bluechi-tester-1` and `bluechi-tester-2` in this test case.
> Fix agent-flood

- tests/e2e/lib/diskutils
- tests/e2e/set-ffi-env-e2e
- tests/ffi/disk/test.sh
- tests/ffi/memory/main.fmf
- tests/ffi/qm-oom-score-adj/main.fmf
Updating tests/e2e/set-ffi-env-e2e to mkfs.ext4
On free sde partiton it finds VROOM-21987
> Add support for SoC separate var partition

- tests/e2e/dashboard-tui/car-dashboard
replace subprocess with invoke it's safer even for a test/demo only code.
> e2e: car-dashboard - use invoke

- tests/e2e/lib/diskutils
- tests/ffi/agent-flood/main.fmf
- tests/ffi/disk/test.sh
- tests/ffi/qm-oom-score-adj/test.sh
test has being failing, let's retry to catch the
pid 10x before exiting.
Fixes: https://github.com/containers/qm/issues/523
> oom-score: retry in case container pid not ready

- qm.if
These rules are collected for an scenario
where a Qemu KVM container runs with GTK
display and Wayland compositor.
> qm.if: qemu + gtk display with wayland

- qm.if
Fixes: https://issues.redhat.com/browse/RHEL-56385
> Allow qm_t ipc_lock capabilty

- tests/e2e/set-ffi-env-e2e
Fix #521 
This is a REBASE for patch for set-ffi-env-e2e forth to #521 .
It checks if the QM rpm package was installed on host.
> Rebase for Check if QM is installed

- rpm/qm.spec
- tests/e2e/lib/diskutils
partprobe requires parted, blockdev uses util-linux-core which most distros ship it in different archs.
> test: replace partprobe with parted

- tests/e2e/lib/diskutils
- tests/ffi/qm-oom-score-adj/test.sh
PR based on this #538 
Tested on soc c9s manually
> /var/qm test

- .packit.yaml
Add support to EPEL10 releases
> packit: add support to EPEL10

- tests/ffi/disk/test.sh
During the work of post install /var/qm partition
podman rmi throws error of full diskspace on cleanup,
This error fails the test on SoC HiL
> Adding fix in qm cleanup for disk tests

- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_systemd_journal_socket.sh
If host do not have the socket, let's fail right away
> check_run_systemd_journal_socket: add fail case for socket

- qm.container
Add new settings for [Service]
See-Also: https://gitlab.com/CentOS/automotive/src/automotive-image-builder/-/merge_requests/102
> qm.container: add MemoryMax and MemoryHigh

- tests/ffi/qm-oom-score-adj/test.sh
Run qm-oom-score-adj alone it will pass, but if run it with other test cases (under /tests/ffi), it will fail.
So improved the cleanup steps.
resolve https://github.com/containers/qm/issues/576
> imporve the cleanup steps

- qm.if
This rule covers the ase of a qm_container_kvm_t
container (e.g., containerized qemu) to work
with dbus display.
Also covers the usecase for vhost-user devices,
as they use unix sockets to communicate with the
VMM (that is, assuming they also use the
qm_container_kvm_t type label).
> qm.if: allow kvm connectto unix_stream_socket

- .github/CODEOWNERS
Felicia has being working in docs in the entire automobile project. I would like to suggest Felicia as co-maintainer of QM project so she is able to keep her sharp eyes in the docs and in the project as well so we follow all the docs good practices and also make sure we include in our new patches documentation so in few year nobody get lost.
> CODEOWNERS: add kleinffm for CODEOWNERS

- docs/qm containers.conf/README.md
- tests/ffi/common/prepare.sh
Fix: ostree images, pulling container larger than 0.9M 
Container with size > 1G is failing and resulting no disk space on podman pull
resolve #574 
The fix creates a workaround for OStree images to properly use prepare.sh.
Rebased from https://github.com/containers/qm/pull/575
Adds OStree image specific checkup to the prepare.sh and sets image_copy_tmp_dir="/var/tmp.dir", so the prepare_images section could be used also for OStree images.
> podman pull, inside qm, fails on OStree image: no space left on device 

- docs/devel/README.md
- tools/version-update
Create a script to ease version managing for
maintainers and developers. The script will handle updating the version in all required files
consistently.
By default, if no new version is provided, the
script increases the minor version by 1.
Otherwise, a specific version can be set with:
$ tools/version-update --version 1.0
And the tools will just perform the changes in
all the relevant files.
> tools/version-update: script to manage version

- .packit.yaml
Is there a reason why you don't want to use aliases such as `fedora-all`, `fedora-branched` or `epel-all`?
> Add Fedora 41 and drop Fedora 38 from Packit config

- Makefile
- etc/qm/containers/containers.conf.d/qm_dropin_mount_bind_input.conf
- rpm/qm.spec
QM sub-package qm_dropin_mount_bind_input will configure via drop-in /dev/input to allow nested containers to automatically see devices like: Keyboards, Mice, Touchpads, Joysticks, Multimedia keys and Device files like /dev/input/event0, /dev/input/event1, etc.
Just execute: make qm_dropin_mount_bind_input
> qm sub-package qm_dropin_mount_bind_input

- .packit.yaml
This merge request updates the `.packit.yaml` configuration file to replace the existing Fedora and EPEL branch targets with architecture-specific branches for aarch64, ppc64le, and x86_64. The updated branches ensure that builds are now targeted for the respective architectures.
- Updated Fedora branch targets from `fedora-rawhide`, `fedora-41`, `fedora-40`, and `fedora-39` to `fedora-all-aarch64`, `fedora-all-ppc64le`, and `fedora-all-x86_64`.
- Updated EPEL branch targets from `epel-9` and `epel-10` to `epel-all-aarch64`, `epel-all-ppc64le`, and `epel-all-x86_64`.
These changes align the branch targets with architecture-specific builds to improve accuracy in handling package distribution for different systems.
> Update Fedora and EPEL branch targets to architecture-specific branches in .packit.yaml

- Makefile
- etc/qm/containers/containers.conf.d/qm_dropin_mount_bind_ttyUSB0.conf
- rpm/qm.spec
Another ready to use example in-tree to users.
Execute: make qm_dropin_mount_bind_ttyUSB0 and voi-la.
> qm sub-package qm_dropin_mount_bind_ttyUSB0

- tests/e2e/set-ffi-env-e2e
It fails script on non c9s distros
> Remove -e from set-ffi-env-e2e

- Makefile
- docs/devel/README.md
Call the update-version script from the
rpm target in the makefile and remove it
from all the subpackage targets, so that
we have a single point of failure and
avoid code repetition.
> makefile: update version in rpm target

- Makefile
- README.md
- etc/qm/containers/containers.conf.d/qm_dropin_mount_bind_kvm.conf
- rpm/qm.spec
The QM sub-package KVM includes drop-in configuration that enables the integration of Kernel-based Virtual Machine (KVM) management into the QM (Quality Management) container environment. This configuration allows users to easily configure and manage KVM virtual machines within the QM system, streamlining virtualization tasks in containerized setups.
Use: make qm_dropin_mount_bind_kvm
> qm sub-package Kernel-based Virtual Machine (KVM)

- Makefile
- README.md
- etc/containers/systemd/ContainerFile.rear-camera
- etc/containers/systemd/rear-camera.container
- etc/qm/containers/containers.conf.d/qm_dropin_mount_bind_video.conf
- rpm/qm.spec
In a typical vehicle system, cameras are connected to the car's onboard computer via a CAN bus (Controller Area Network), which transmits signals from the cameras to the car’s system for real-time processing. This is commonly used for functions like parking assistance, lane-keeping, or 360-degree surround-view systems.
However, it's possible to create a simulation environment using traditional hardware and open-source software, eliminating the need for actual car cameras or CAN bus integration. By using open-source tools like Podman containers and video processing libraries (such as GStreamer or FFmpeg), virtual cameras can be simulated. These tools allow developers to simulate the video signals typically produced by physical car cameras and routed through the CAN bus.
In this setup, …
> qm subpackage: simulate car cameras using OSS

- tests/ffi/main.fmf
When using tmt `prune` (Copy only immediate directories of executed tests and their required files. Added in version 1.29.) in the test plan, need to specify the location of the included file, otherwise an error will occur.
> add support for tmt prune

- Makefile
- docs/devel/README.md
- rpm/qm.spec
Adding support in build env vars 
This set rpmbuild --define vars in Makefile. 
remove define vats for building subpackages
Toggle package to build by define export variable=1
> Adding VARIABLES for subpackages build

- Makefile
- rpm/qm.spec
- tools/qm-is-ostree
- Updated Makefile to install the qm-is-ostree script to ${DATADIR}/qm/
- Modified qm.spec to include qm-is-ostree in the install and package files
- Added the qm-is-ostree script to the RPM pre uninstall steps
Signed-off-by: Rakesh Musalay <rmusalay@redhat.com>
Address the issue https://github.com/containers/qm/issues/586
Summary of Changes
Makefile Updates:
Added a new installation step for the qm-is-ostree script.
The script tools/qm-is-ostree is installed as qm-is-ostree with executable permissions (755) to the target directory ${DATADIR}/qm/.
RPM Spec File (qm.spec) Modifications:
Added an entry to install the qm-is-ostree script in the %install section at /usr/share/qm/qm-is-ostree.
Updated the list of packaged files to include %{_datadir}/qm/qm-is-ostree, ensuring the script is …
> Add qm-is-ostree script installation and RPM packaging

- rpm/qm.spec
During service start in Fedora it try to read
qm.container from /etc/containers/systemd/qm.container instead of /usr/share/qm/qm.container and fails
as it's a ghost (empty) file.
> spec: remove ghost entry for qm.container

- tests/ffi/disk/main.fmf
Add a NoRenesas tag to /tests/ffi/disk to disable it when there is no separated /var disk partition for QM.
> add NoRenesas tag to /tests/ffi/disk

- plans/e2e/ffi.fmf
- plans/main.fmf
- tests/e2e/README.md
- tests/e2e/set-ffi-env-e2e
resolve #642 
Prepare Fedora image for testing
Changing the copr repositories to more genereric way
README explains how to tests copr PR rpm on local vm
For cases without /etc/os-release added distro context
to env-variable convert in main plan
> Fedora-support

- .packit.sh
- Makefile
- docs/devel/README.md
- rpm/qm.spec
- tests/e2e/set-ffi-env-e2e
Rebase latest changes
Adding howto create PR subpackages
Part of #624
>  Adding extra packages to fix-spec-file

- tests/ffi/sys_read_only/PURPOSE
- tests/ffi/sys_read_only/README.md
- tests/ffi/sys_read_only/main.fmf
- tests/ffi/sys_read_only/test.sh
Test to ensure that /sys is read-only inside the
QM container.
> tests/ffi: add test checking /sys is read-only

- containers.conf
- plans/e2e/kvm-tier-0.fmf
- plans/main.fmf
- setup
- tests/e2e/lib/repoutils
- tests/e2e/lib/utils
- tests/e2e/set-ffi-env-e2e
- tests/qm-sanity-test/check_qm_podman_quadlet_is_ok.sh
- tests/qm-sanity-test/check_qm_podman_ulimits_are_set.fmf
- tests/qm-sanity-test/check_qm_podman_ulimits_are_set.sh
- tests/qm-sanity-test/check_qm_setup_succeeds.fmf
This commit fix #666, till full support in podman
Fedora tests run only on kvm-tier-0,
test setup script, first, then apply rlimit test fix
c9s fix, inside prepare script set-ffi-env-e2e
Update util exec_cmd to print successful commands,
> Add fedora fix

- tests/ffi/disk/test.sh
Added a function `check_var_partition` to check if a separate /var disk partition exists before executing the test, so as not to block the execution of other test cases after it.
> check /var partition before run /tests/ffi/disk

- rpm/qm.spec
- setup
- netavark requires ip_tables, otherwise podman complains
- removed in %post isostres command (not required at all)
> fix requirement of modprobe ip_tables

- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_console.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_disk.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_kmsg.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_etc_qm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_lib_qm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_share_qm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/check_dev_shm.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_systemd_journal_socket.fmf
- tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_udev_control.fmf
- tests/ffi/dev_mem_not_present/main.fmf
Test metadata information was added to the following cases:
- https://github.com/containers/qm/tree/main/tests/ffi/attempts_to_access_forbidden_file_system_resource
- https://github.com/containers/qm/tree/main/tests/ffi/dev_mem_not_present
- https://github.com/containers/qm/tree/main/tests/ffi/sys_read_only
> Adding test metadata for validators

- .packit.yaml
- plans/e2e/aib.fmf
- tests/aib/check_qm_with_aib.fmf
- tests/aib/check_qm_with_aib.sh
Introducing a new sanity test, that builds a basic qm image with automotive-image-builder.
Resolves:  #675
> Add test to run basic qm image build with a-i-b

- qm.te
- rpm/qm.spec
Fixes: https://github.com/containers/qm/issues/677
Recently, BlueChi enhanced the support for Unix Domain Sockets, including the respective SELinux policy (see In eclipse-bluechi/bluechi#1015). On a setup QM + BlueChi it makes sense to mount the UDS of BlueChi into QM and have the bluechi-agent inside connect to it. This, however, is currently rejected due to missing SELinux policy rules. Let's add this rule.
> Add bluechi uds to policy

- plans/e2e/aib.fmf
auto-image-builder.sh now uses jq. Adding jq to the prepare step for automotive-image-builder test plan
> Add jq package installation to a-i-b test

- qm.container
Add comments to [container] section under qm quadlet file
upstream doc reference added to each quadlet param,
> Adding comments for container options in qm.container

- README.md
"Add documentation for adjusting OOM scores in nested containers
This adds comprehensive documentation on how to customize OOM score 
adjustment for nested containers running inside QM, including:
- Step-by-step configuration of nested container Quadlet files
- QM drop-in configuration for required capabilities  
- Verification process using podman-system-generator
- Testing procedures with expected OOM score values
The documentation shows how to set different OOM priorities for 
nested containers (1000 vs 100) to control OOM killer behavior.
Closes https://github.com/containers/qm/issues/899
> Add documentation for overriding QM attributes using drop-in files
