containers/qm

qm.if, qm.spec.rpkg, qm_selinux.8
This will allow unconfined domains to manage these types.
=> Identify qm_container_file_t as a file_type

Makefile, qm.8.md, qm.spec.rpkg
Document how to use the qm environment.
=> Add man page for qm

setup
* Make sure script is run as root
* Remove sudo calls since the script will be run as root
* On systems that require gpgcheck, we need to first copy in the existing /etc/pkg/rpm-gpg directory into the ROOTFS cp /etc/pkg/rpm-gpg $ROOTFS/etc/pkg
=> Cleanup setup script

qm.spec.rpkg
=> rpm: podman on Fedora has Epoch: 5

Makefile, qm.container, qm.spec.rpkg
/etc/containers/systemd/qm.container is for administrators to modify
Also run containers in the qm with level s0
=> Install qm.container in /usr/share/containers/systemd

.packit.yaml
=> Packit: Explicitly specify all copr build targets

tests/e2e/lib/container, tests/e2e/lib/systemd, tests/e2e/lib/tests, tests/e2e/lib/utils, tests/e2e/run-test-e2e
The script was ready but missing to check if the commands really executed correctly. This patch adds such ability in all calls.
=> e2e: add validations for calls 

qm.container
fuse is required for nested container
=> qm.container: add /dev/fuse

.github/CODEOWNERS
Automatically add owners to review new PRs.
=> build: add .github/CODEOWNERS

rpm/qm.spec
Ref: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2023-9edad6c8f4
=> RPM: adjust podman dependency epoch

qm.te
@rhatdan @dougsland PTAL
@rhatdan would be nice to cut v0.2.1, but your call.
=> qm.te: Bump version

rpm/qm.spec
@rhatdan @dougsland @pypingou PTAL
=>  RPM: account for nproc == 1 and update correct quadlet file

demos/dashboard-tui, tests/e2e/dashboard-tui/README.md, tests/e2e/dashboard-tui/car-dashboard
Initial dashboard-tui tool, requires tests/e2e/run-test-e2e to setup the environment. After that, just run the tool.
=> demo/e2e: add dashboard-tui

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, demos/asilservice.py, demos/demo, qm.container
Adding demo path for flake8 check
=> Adding flake8 to precommit

tests/e2e/lib/ContainerFile.template
Adds:
- python3-gobject, python3-pip
- alias from python3 to python
Resolves:
https://github.com/containers/qm/issues/78
https://github.com/containers/qm/issues/71
=> template: add more python packages and link

tests/e2e/lib/container, tests/e2e/run-test-e2e
=> e2e: add dual stack support

.packit.sh
make .packit.sh pass shellcheck
=> make .packit.sh pass shellcheck

.pre-commit-config.yaml, README.md, SECURITY.md, qm.8.md, tests/e2e/README.md, tests/e2e/dashboard-tui/README.md
Fix markdown and make it pass pre-commit hook.
=> markdown: make it pass markdownlint

rpm/update-spec-version.sh
make shellcheck pass on update-spec-version.sh
=> update-spec-version.sh shellcheck fixes

setup
pre-commit hook requires to pass shellcheck but existing code didn't pass the test.
=> make setup pass shellcheck

.pre-commit-config.yaml, tests/e2e/lib/tests, tests/qm-connectivity/test.sh
fixed issues detected by shellcheck on qm connectivity test.
=> fix connectivity test shellcheck

tests/e2e/lib/tests
PR resolves #118
It seems that we were to quick to merge
=> Fix linting issue

qm.container
Fixes: https://github.com/containers/qm/issues/113
=> Default timezone to local to match the hosts

tests/e2e/README.md
Adding section to tests/e2e/README.md how run test locally
Describe how to run tests with TMT
=> Adding steps how to test qm manually

tests/e2e/lib/ContainerFile.template, tests/e2e/lib/container
During inspection of systemctl start qm failures
It seems that config files were not set properly due to regexp inaccuracies
=> Fix hirtectl config

demos/asilservice, demos/demo
- check errors in commands
- auto add node names into hirte config
- general improvements in the demo script
Resolves: https://github.com/containers/qm/issues/103
=> demo: general improvements

README.md, docs/quadlet-examples/virtualization/android/README.md
Initial commit provided by Dan Walsh running android container on top of kvm + wayland.
=> docs: Adding docs/quadlet-examples dir

tests/e2e/README.md
Minor changes to improve the doc.
=> e2e: update doc for tmt locally

rpm/qm.spec
=> spec: target /usr/lib for qm module

qm.if
Allow qm containers to search through qm_file_t directories. 
Allow qm containers to search through sysfs file system directories.
=> Allow qm container domains additional access

tests/e2e/lib/container
Now that we have a ability to create 'N' nodes
we need to add it to AllowedNodeNames too.
=> e2e: update lib/container to add node'N' nodes

tests/e2e/lib/utils, tests/e2e/run-test-e2e
Now remove all containers dynamic created.
=> e2e: run-test-e2e improve cleanup

.github/CODEOWNERS
- Yariv has being helping us in the QE side
- Sandro has being helping us in the tests for the virtualization platform
and fedora packaging
Both understand and uses QM in different ways, if possible, i would like to add them as owners and reviewers of the code to keep our quality high.
=> CODEOWNERS: Yariv and Sandro

tests/e2e/lib/tests, tests/e2e/run-test-e2e
=> e2e: create systemd stub srv in all qm nodes

tests/e2e/lib/tests
=> e2e: list only services created by the test script

tests/e2e/lib/utils, tests/e2e/run-test-e2e
=> e2e: add more info regarding the tests

tests/e2e/run-test-e2e
=> e2e: add days and hours for the e2e tests measure

tests/e2e/lib/ContainerFile.template
- ShellCheck: validate sh scripts
- python8-flake: add flake8 tool
Additionally, replaced some spaces with tabs.
=> e2e: add more tools for development

tests/e2e/lib/ContainerFile.template
pre-commit has several validations that can be used during development.
=> e2e: add pre-commit tool to validate code

tests/e2e/lib/ContainerFile.template
Performance Co-Pilot (PCP) provides a framework and services to support system-level performance monitoring and performance management. Useful for development and testing.
Fixes: https://github.com/containers/qm/issues/174
=> e2e: add pcp package

README.md, demos/demo, qm.8.md, rpm/qm.spec, setup, tests/e2e/README.md, tests/e2e/dashboard-tui/README.md, tests/e2e/dashboard-tui/car-dashboard, tests/e2e/lib/ContainerFile.template, tests/e2e/lib/container, tests/e2e/lib/tests, tests/e2e/run-test-e2e, tests/e2e/tier-0.fmf, tests/qm-connectivity/test.sh
Hirte project has being renamed to BlueChi.
=> rename hirte to bluechi

setup
Adding a "SYSTEMCTL_SKIP" en var make tit container build friendly.
=> SYSTEMCTL_SKIP env var

demos/demo
=> demos: add copr for bluechi

Makefile
Fixes: https://github.com/containers/qm/issues/177
=> makefile: change $$NAME to $$ID and add autosd

tests/e2e/lib/ContainerFile.template
=> e2e: add rust support

tests/e2e/dashboard-tui/car-dashboard
=> car-dashboard: fix typo

tests/e2e/lib/ContainerFile.template, tests/e2e/lib/container
Bluechid configuration files renamed from
bluechi.cong -> controller.conf
Updates scripts and Container files based on that
=> Fix due to renaming of bluechid to controller

setup
Fixes: https://github.com/containers/qm/issues/223
=> setup: make sure create rootfs req dirs

tests/e2e/lib/ContainerFile.template
Fixes: https://github.com/containers/qm/issues/227
=> e2e: add packages to build podman

.github/CODEOWNERS
=> Adding odra to CodeOwners

.packit.yaml
Resolve #250 
Currently remove it from packit tests, and not from tmt, till stability and container gating are solved stable
=> Remove tier-1 test

tests/e2e/lib/ContainerFile.template
This PR fix skipped corrections in issue #255 in order to pass gating
=> Fix issue #255

demos/demo, tests/e2e/lib/ContainerFile.template, tests/e2e/set-ffi-env-e2e
Resolve #257
Update bluechi repo to centos-automotive-sig/bluchi-snapshots
=> Bluechi repo fix

.packit.yaml, tests/e2e/set-ffi-env-e2e, tests/ffi/common/prepare.sh, tests/ffi/disk/main.fmf, tests/ffi/disk/test.sh, tests/ffi/memory/test.sh
Adding test /tests/ffi/disk
The test create partition on /var/qm/ and checks if
non-qm partition / is free with disk space
~PR is created from #212 branch. moving to draft~
FFI tests needs special HW, that will be parsed to packit.
=> Add memory test 

plans/e2e/tier-1.fmf, tests/e2e/lib/tests, tests/e2e/lib/utils, tests/qm-connectivity/main.fmf, tests/qm-connectivity/test.sh
Tier-1 test was failing when running against AutoSD container.
Test is not running in CI gate, for now 
Sleep and command change was needed to make it work.
=> Fixing tier-1 tests

tests/e2e/lib/container, tests/e2e/run-test-e2e
Fixes: https://github.com/containers/qm/issues/316
=> e2e: qm-nodes: move NodeName logic to a function

.packit.yaml, tests/e2e/set-ffi-env-e2e
With introduction of vsomeip-selinux
as build dependency c9s target build is failing
resolve https://github.com/containers/qm/issues/299
=> Fixing broken gate

tests/ffi/agent-flood/main.fmf, tests/ffi/disk/main.fmf, tests/ffi/memory/main.fmf, tests/ffi/qm-unit-files/main.fmf, tests/qm-connectivity/main.fmf, tests/qm-unit-files/main.fmf
adding tmt ids to every test 
.fmf files reformatted through tmt lint
=> Adding test ids to already existing tests + tmt lint reformatting

tests/ffi/agent-flood/main.fmf
Just replaced summary
Fixes: https://github.com/containers/qm/issues/305
=> tests: fix summary agent-flood/main.fmf

tests/e2e/tools/FFI/Makefile
Revert the Makefile to before adding SharedMemory
=> revert to before adding shm

qm.container
podman recent versions should support it.
=> qm.container: add back SecurityLabelNested=True

qm.container, tests/ffi/common/prepare.sh
Previously we removed the removed the readonlytmp, adding back.
=> qm: add back readonlytmp

tests/ffi/common/prepare.sh
yariv reported that updating kernel resolved the issue.
Fixes: #360
=> tests: remove fix-me regarding oom killer

rpm/qm.spec
during uninstall make sure to remove the generated speccomp.json
=> spec: make sure remove speccomp.json

tests/ffi/common/prepare.sh
I cannot reproduce this error, removing fixme.
Fixes: https://github.com/containers/qm/issues/359
=> prepare.sh: remove FIX-ME regarding restorecon

Makefile, qm.8.md, rpm/qm.spec, setup, tools/qm-rootfs
If we created, we must remove it.
Fixes: https://github.com/containers/qm/issues/401
=> qm: make sure remove rootfs when uninstalling

docs/devel/README.md
=> docs: Add more info to devel README

.packit.yaml
fedora40 was released let's add it to packit.
=> packit: add fedora40 to the list

tests/e2e/tools/FFI/Makefile
Add the tool "test_sched_setscheduler " according to https://github.com/containers/qm/issues/365
=> add tool test_sched_setscheduler

docs/devel/README.md
Update devel README file to reflect
latest updates with sample-images
and automotive-image-builder commands
and project structures.
=> docs: Update devel readme

tests/ffi/selinux/main.fmf
=> create a test case for setenforce 0 - create polarion TC

demos/devconf-2024/README.md, demos/devconf-2024/prepare-demo.sh, tests/e2e/lib/systemd, tests/e2e/lib/utils
Updating lib/systemd run against non qm image
This PR enables the creation of demo services on non
containerized environment
Signed-off-by: Yariv Rachmani <yrachman@redhat.com>
=> Devconf update

tests/ffi/tcp_max_syn_backlog/main.fmf
Added a patch to main.fmf, increased duration time from 20 min to 30 min.
=> Add patch to main.fmf increased time to 30 min

demos/devconf-2024/README.md
=> Fixing Demo readme

tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/PURPOSE, tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_console.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_disk.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/devices/check_dev_kmsg.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/PURPOSE, tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_etc_qm.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_lib_qm.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/regular_os_files/check_usr_share_qm.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/PURPOSE, tests/ffi/attempts_to_access_forbidden_file_system_resource/shared_memory_files/check_dev_shm.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/PURPOSE, tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_systemd_journal_socket.fmf, tests/ffi/attempts_to_access_forbidden_file_system_resource/sockets/check_run_udev_control.fmf
=> Set test id

tests/ffi/common/prepare.sh, tests/ffi/qm_nested/test.sh
This is a rebase from https://github.com/containers/qm/pull/510 .
=> Rebase for qm_nested patch

.github/workflows/check-cgroup.yml
Display the cgroup version from the worker
=> gh actions: add cgroup checker

.github/workflows/check-python-bandit, .github/workflows/check-with-bandit.yml
github actions workflow to check python code using bandit.
=> workflow: add bandit check

tests/ffi/agent-flood/main.fmf
fixed agent-flood by ffi-tools https://gitlab.com/CentOS/automotive/container-images/ffi-tools/-/merge_requests/34
resolve https://github.com/containers/qm/issues/534
=> add back agent-flood

Makefile
Thanks for @aesteve-rh for the suggestion!
=> makefile: replace make with $(MAKE)

Makefile
@aesteve-rh's tool worked in one target, let's update all others.
=> makefile: use update-version tool

README.md
=> README: fix pre-commit warnings

tests/e2e/set-ffi-env-e2e
Under CI special case exist.
rpm qm is installed in c9s machine, but setup
script that emulate the QM environment is not set
=> Added fix to c9s

Makefile
Recently we changed the way to do builds, adding the missing \
=> Makefile: fix missing \

Makefile
reduce payload in the dist target
=> Makefile: reduce payload in dist target

.pre-commit-config.yaml, .pre-commit-hooks.yaml, pre-commit-hooks/validate-config.sh
=> Add packit pre-commit

tests/qm-sanity-test/check_qm_setup_succeeds.fmf
=> test: add check_qm_setup_succeeds

Makefile, README.md, rpm/qm.spec, subsystems/ros2/ContainerFile, subsystems/ros2/ros2-rolling.container
Just initial work to support ROS2 - "The Robot Operational System" (The middleware for robots) out of box into QM.
ContainerFile by Leonardo Rossetti <lrossett@redhat.com> with few mods by me.
See-Also: https://ros.org/
=> Add ROS2 subpackage into QM

.github/workflows/drop-in-target-build-only.yml, docs/devel/README.md, subsystems/ros2/ros2-rolling.container
- ros2-rolling: remove the restart action
- docs: debugging quadlets
=> General improvements

setup
It will solve the recent CI/CD setup install complain about not able to find packages.
=> setup: for fedora use --use-host-config for dnf repos

README.md, rpm/qm.spec, subsystems/audio/ContainerFile, subsystems/audio/audio.container
Add audio dir with ContaineFile with all packages required for quadlets when the subject is add initial audio support.
=> subsystem: add audio dir

Makefile, rpm/text2speech/text2speech.spec, tools/version-update
When adding base robotic to QM, it's always good to have text2speech available for development. Specially for demos, talks.
=> text2speech: add espeak to QM

.packit.yaml
Relates to: https://github.com/containers/qm/issues/677
Added bluechi copr repo as additional repo to epel10 copr build job target
=> Added epel10 additional repos to copr build

tools/qmctl/README.md, tools/qmctl/qmctl
Initial commit
New Features:
- Introduce a new command-line utility (qmctl) for managing queue managers
Implement #782  close #782
=> qmctl - QM control tool
